version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: streamdb
      POSTGRES_USER: streamuser
      POSTGRES_PASSWORD: streampassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  zookeeper:
    image: wurstmeister/zookeeper:3.4.9
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  flink-jobmanager:
    image: flink:1.14.4-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-taskmanager:
    image: flink:1.14.4-scala_2.12
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  data-generator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.generator
    depends_on:
      - postgres
      - kafka
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: